<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE figis:object [	<!ENTITY NS "http://www.fao.org/figis">	<!ELEMENT figis:object ANY>	<!ATTLIST figis:object		name CDATA #REQUIRED		xmlns:figis CDATA #FIXED "http://www.fao.org/figis"		id CDATA #IMPLIED	><!ELEMENT figis:coords (#PCDATA)><!ELEMENT figis:description (#PCDATA)><!ELEMENT figis:fid (#PCDATA)><!ELEMENT figis:image (#PCDATA)><!ELEMENT figis:name (#PCDATA)><!ELEMENT figis:neighbour (#PCDATA)><!ELEMENT figis:target (#PCDATA)>]><figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModel">	<figis:description>Top level water areas</figis:description>	<figis:object xmlns:figis="&NS;" id="0" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelNode">		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">			<figis:fid>0</figis:fid>		</figis:object>		<figis:image>/fi/figis/assets/maps/water/w0.gif</figis:image>		<!-- the polygon target areas -->		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>8</figis:fid>					</figis:object>					<figis:name>1=Arctic Sea</figis:name>					<figis:name>21=18</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(122,16)(183,17)(181,56)(150,33)(139,40)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>8</figis:fid>					</figis:object>					<figis:name>1=Arctic Sea</figis:name>					<figis:name>21=18</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(65,55)(83,35)(92,45)(88,47)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>10</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Northeast</figis:name>					<figis:name>21=27</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(181,56)(150,33)(130,40)(128,61)(98,65)(70,110)(119,121)(124,90)(158,63)(168,68)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>2</figis:fid>					</figis:object>					<figis:name>1=Inland waters - America, North</figis:name>					<figis:name>21=02</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(122,16)(139,40)(128,61)(98,65)(120,40)(111,39)(97,51)(92,45)(83,35)(65,55)(88,47)(79,73)(22,90)(62,43)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>5</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Europe</figis:name>					<figis:name>21=05</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(119,121)(124,90)(158,60)(168,68)(165,102)(164,114)(147,104)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>9</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Northwest</figis:name>					<figis:name>21=21</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(39,85)(79,73)(88,47)(92,45)(97,51)(111,39)(120,40)(98,65)(70,110)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>13</figis:fid>					</figis:object>					<figis:name>1=Mediterranean and Black Sea</figis:name>					<figis:name>21=37</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(119,121)(147,104)(164,114)(165,102)(188,106)(177,130)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>11</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Western Central</figis:name>					<figis:name>21=31</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(70,110)(39,85)(20,94)(8,128)(37,162)(55,165)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>12</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Eastern Central</figis:name>					<figis:name>21=34</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(119,121)(70,110)(55,165)(70,169)(88,194)(143,197)(139,176)(108,175)(94,157)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>3</figis:fid>					</figis:object>					<figis:name>1=Inland waters - America, South</figis:name>					<figis:name>21=03</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(8,128)(63,196)(40,255)(8,197)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>14</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Southwest</figis:name>					<figis:name>21=41</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(37,162)(70,170)(88,194)(99,270)(61,275)(40,255)(63,196)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>4</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Asia</figis:name>					<figis:name>21=04</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(188,106)(177,130)(201,159)(229,129)(258,154)(262,119)(282,135)(294,174)(289,115)(267,74)(239,46)(224,106)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>15</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Southeast</figis:name>					<figis:name>21=47</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(88,194)(143,197)(154,244)(173,246)(169,269)(99,270)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>16</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Antartic</figis:name>					<figis:name>21=48</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(99,270)(61,275)(112,300)(162,305)(169,269)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>1</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Africa</figis:name>					<figis:name>21=01</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(177,130)(119,121)(94,157)(108,175)(139,176)(143,197)(154,244)(173,246)(210,171)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>1</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Africa</figis:name>					<figis:name>21=01</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(204,230)(201,240)(213,206)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>17</figis:fid>					</figis:object>					<figis:name>1=Indian Ocean, Western</figis:name>					<figis:name>21=51</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(173,246)(171,263)(239,264)(262,204)(258,154)(229,129)(201,159)(210,171)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>19</figis:fid>					</figis:object>					<figis:name>1=Indian Ocean, Antartic</figis:name>					<figis:name>21=58</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(171,263)(239,264)(225,285)(163,304)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>18</figis:fid>					</figis:object>					<figis:name>1=Indian Ocean, Eastern</figis:name>					<figis:name>21=57</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(225,285)(239,264)(262,204)(258,154)(262,119)(282,135)(294,174)(278,228)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>7</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Former USSR area</figis:name>					<figis:name>21=07</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(239,46)(224,106)(188,106)(165,102)(168,68)(181,56)(183,17)</figis:coords>			</figis:object>		</figis:object>		<figis:neighbour>NORTH=2</figis:neighbour>		<figis:neighbour>SOUTH=2</figis:neighbour>		<figis:neighbour>EAST=1</figis:neighbour>		<figis:neighbour>WEST=3</figis:neighbour>	</figis:object>	<figis:object xmlns:figis="&NS;" id="1" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelNode">		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">			<figis:fid>1</figis:fid>		</figis:object>		<figis:image>/fi/figis/assets/maps/water/w90.gif</figis:image>		<!-- the polygon target areas -->		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>7</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Former USSR area</figis:name>					<figis:name>21=07</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(47,56)(84,71)(145,44)(192,54)(209,26)(152,12)(92,25)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>4</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Asia</figis:name>					<figis:name>21=04</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(47,56)(84,71)(145,44)(192,54)(162,97)(149,115)(125,93)(104,114)(77,89)(54,121)(29,77)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>1</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Africa</figis:name>					<figis:name>21=01</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(54,121)(29,77)(6,127)(9,201)(46,226)(37,162)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>1</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Africa</figis:name>					<figis:name>21=01</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(57,166)(51,182)(62,194)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>17</figis:fid>					</figis:object>					<figis:name>1=Indian Ocean, Western</figis:name>					<figis:name>21=51</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(46,226)(37,162)(54,121)(77,89)(104,114)(118,216)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>15</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Southeast</figis:name>					<figis:name>21=47</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(46,226)(9,201)(56,276)(73,246)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>18</figis:fid>					</figis:object>					<figis:name>1=Indian Ocean, Eastern</figis:name>					<figis:name>21=57</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(118,216)(104,114)(125,93)(149,115)(130,128)(192,155)(164,171)(168,192)(212,209)(197,236)(124,233)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>19</figis:fid>					</figis:object>					<figis:name>1=Indian Ocean, Antartic</figis:name>					<figis:name>21=58</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(46,226)(73,246)(106,268)(143,247)(182,257)(197,236)(124,233)(118,216)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>26</figis:fid>					</figis:object>					<figis:name>1=Pacific, Antartic</figis:name>					<figis:name>21=88</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(182,257)(162,285)(184,287)(167,304)(218,290)(197,236)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>22</figis:fid>					</figis:object>					<figis:name>1=Pacific, Western Central</figis:name>					<figis:name>21=71</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(274,215)(228,187)(192,155)(130,128)(149,115)(162,97)(284,106)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>16</figis:fid>					</figis:object>					<figis:name>1=Atlantic, Antartic</figis:name>					<figis:name>21=48</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(56,276)(73,246)(106,268)(111,291)(167,304)(99,299)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>8</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Antartic</figis:name>					<figis:name>21=08</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(106,268)(143,247)(182,257)(162,285)(184,287)(167,304)(111,291)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>24</figis:fid>					</figis:object>					<figis:name>1=Pacific, Southwest</figis:name>					<figis:name>21=81</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(197,236)(218,290)(284,222)(274,215)(228,187)(212,209)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOListNode">				<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOComplexName">					<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.util.common.FAOObject">						<figis:fid>6</figis:fid>					</figis:object>					<figis:name>1=Inland waters - Oceania</figis:name>					<figis:name>21=06</figis:name>				</figis:object>			</figis:object>			<figis:target>true</figis:target>			<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOPolygon">				<figis:coords>(212,209)(228,187)(192,155)(164,171)(168,192)</figis:coords>			</figis:object>		</figis:object>		<figis:object xmlns:figis="&NS;" name="org.fao.fi.figis.statapplet.presentation.gui.FAOMapModelTargetArea">			<figis:object xmlns:figis="&